CREATE TABLE transacoes (
    id SERIAL PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
    tipo_transacao VARCHAR(50) NOT NULL, -- Ex: 'DEPOSITO', 'PAGAMENTO_ALUGUEL', 'RECEBIMENTO_ALUGUEL', 'PAGAMENTO_DEVOLUCAO', 'RECEBIMENTO_DEVOLUCAO'
    valor NUMERIC(10, 2) NOT NULL,
    data_transacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);